### ISSUE TITLE
https://debian.fhem.de/fhem.deb kann nicht aufgelöst werden

### ISSUE THREAD

**Issue by mac321321** [klein0r/fhem-docker#1]
Hi Matthias,
ich habe leider das Problem, dass in **fhem-docker/fhem/Dockerfile** "https://debian.fhem.de/fhem.deb" nicht aufgelöst werden kann. Ist https hier wirklich korrekt?

**Comment by Moneybox76** [comment]
Hallo Matthias,

du musst folgenden Pfad verwenden: https://debian.fhem.de/fhem-5.8.deb

**Comment by Clown007** [comment]
Zur Ergänzung:
RUN wget http://fhem.de/fhem-5.8.deb && dpkg -i fhem-5.8.deb

Es müssen aber vorher noch drei Pakete ergänzt werden, die für aktuelle Version von fhem benötigt werden:
sqlite3 \
libdbd-sqlite3-perl \
libtext-diff-perl

**Comment by klein0r** [comment]
Wurde durch den commit von @legacycode behoben
