### ISSUE TITLE
Fehler bei Installation im Bereich DbLog

### ISSUE THREAD

**Issue by xtolkien** [klein0r/fhem-docker#10]
Ich habe eine Dockerumgebung auf einem Synology-NAS. Die Installation der Container über docker-compose klappt grundsätzlich. Allerdings wirft der FHEM-Container die folgende Fehlermeldung:
"DbLog DBLogging - Error while reading /opt/fhem/contrib/dblog/db.conf: 'could not read connection'"

[fhem.log.txt](https://github.com/klein0r/fhem-docker/files/1853109/fhem.log.txt)

Hier ist die zugehörige docker-compose.yml:

[docker-compose.yml.txt](https://github.com/klein0r/fhem-docker/files/1853104/docker-compose.yml.txt)

Bis auf das Entfernen  der beiden Container Homebridge und habridge habe ich keine Veränderung an Dateien vorgenommen.

**Comment by edi-design** [comment]
Hey,

du musst die DB Zugangsdaten noch in die config eintragen.
`vi ./fhem/core/contrib/configDB/configDB.conf`

```
%dbconfig= (
    connection => "mysql:database=fhem;host=mysql;port=3306",
    user => "fhemuser",
    password => "2jRHnEi3WuNSQAcX7"
);
```

Beste Grüße,
André

**Comment by xtolkien** [comment]
Hi,

danke für die Info, werde ich morgen dann mal machen. Hätte ich eigentlich auch selbst drauf kommen können.

VG
Michael

**Comment by NBFPsycho** [comment]
Hi, 

ich habe exakt dasselbe Problem mit 

"DbLog DBLogging - Error while reading /opt/fhem/contrib/dblog/db.conf: 'could not read connection'".

Die DB Zugangsdaten (fhemuser, 2jRHnEi3WuNSQAcX7) wurden durch die docker-compose.yml bereits automatisch in der Datei "configDB.conf" eingetragen.

Stehe irgendwie auf dem Schlauch. 
Was habe ich falsch gemacht bzw. was muss ich machen, so dass das mySQL Logging funktioniert?

Viele Grüße
Linus

**Comment by NBFPsycho** [comment]
Hallo nochmal,

wahrscheinlich liegt es bei mir an irgendetwas anderem, nach dem "docker-compose up" bekomme ich beim mySQL Server folgende Meldungen und danach bleibt alles stehen. Der mySQL-Container läuft aber zumindest laut Portainer.

Habe testweise alle anderen Container aus der docker-compose.yml bis auf fhem und mySQL entfernt.

[...]
```
mysql_1  | [Entrypoint] MySQL Docker Image 5.7.23-1.1.7
fhem_1   | Starte FHEM
mysql_1  | [Entrypoint] Initializing database
mysql_1  | [Entrypoint] Database initialized
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
mysql_1  | [Entrypoint] GENERATED ROOT PASSWORD: PitWAzYKQazvevEdYf3lYjZHxaJ
mysql_1  |
mysql_1  | [Entrypoint] running /docker-entrypoint-initdb.d/fhem-init.sql
mysql_1  | ERROR: Can't initialize batch_readline - may be the input source is a directory or a block device.
mysql_1  |
mysql_1  | [Entrypoint] Server shut down
mysql_1  |
mysql_1  | [Entrypoint] MySQL init process done. Ready for start up.
mysql_1  |
mysql_1  | [Entrypoint] Starting MySQL 5.7.23-1.1.7
```
Evtl. blockiert irgendetwas den Zugriff?
Kann mir jemand einen Tipp geben?

Die restliche reine Fhem-Installation inkl. Hardware-Interfaces läuft problemlos.

Viele Grüße
Linus

**Comment by NBFPsycho** [comment]
Hat sich erledigt. Nachdem ich alles nochmals komplett gelöscht, neu geklont, gebaut und ausgeführt habe, hat es funktioniert.

Viele Grüße
Linus
