### ISSUE TITLE
Warum finde ich es nicht unter https://hub.docker.com/

### ISSUE THREAD

**Issue by steckenpferd** [klein0r/fhem-docker#13]
Hi Matthias,

wollte mir FHEM im Docker auf der Synology installieren aber unter https://hub.docker.com/ finde ich viele FHEM Docker aber leider nicht dein Packet.
Woran liegt das bzw. könntest du es hinzufügen?

Danke und Gruß

Thomas

**Comment by klein0r** [comment]
Sehr alter Issue, aber der Vollständigkeit halber: Mittlerweile gibt es ein offizielles FHEM Docker Image https://hub.docker.com/r/fhem/fhem
