### ISSUE TITLE
Korrekte Zeitzone in den Containern

### ISSUE THREAD

**Issue by xtolkien** [klein0r/fhem-docker#14]
Mir ist aufgefallen, dass der FHEM-Container auf meinem Synology NAS nach der Installation eine falsche Zeitzone besitzt. Das Dockerfile enthält zwar die Anweisung

"RUN echo Europe/Berlin > /etc/timezone && dpkg-reconfigure tzdata",

dies scheint aber nicht zu wirken. Deshalb habe ich eine andere Lösung gesucht und die Zeitzone über die docker-compose.yml gewählt. Dort habe für jeden Container noch ein command-Tag aufgenommen.

command: >
            /bin/bash -c "ln -snf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && echo 'Europe/Berlin' > /etc/timezone"

Damit wird beim Starten eines Containers die korrekte Zeitzone eingestellt.

VG
Michael

**Comment by benedikt-bartscher** [comment]
Hatte das gleiche Problem, habe aber einfach
`RUN ln -snf /usr/share/zoneinfo/Europe/Berlin /etc/localtime`
zur Dockerfile vom FHEM Container hinzugefügt!

**Comment by petterpet** [comment]
Bei mir war die Zeit auch verkehrt. Habe einfach folgendes Volume mit eingetragen: 
`/etc/localtime:/etc/localtime:ro`
