### ISSUE TITLE
Nutzung von MQTT aus dem FHEM-Container

### ISSUE THREAD

**Issue by xtolkien** [klein0r/fhem-docker#15]
Hallo zusammen,

ich habe Probleme in der Synology Dockerumgebung bei der Einbindung von des MQTT-Containers in den FHEM-Container. Ich habe den folgende define ausgeführt:

define MQTT_SERVER MQTT IP-Adresse:1883

Der Eintrag in FHEM wird auch angelegt, allerdings springt der Status im Sekundentakt von connected zu disconnected. Im Log ist erkennbar, dass FHEM sekündlich versucht, mit identischen Daten eine Verbindung aufzubauen. Der MQTT-Broker schließt dann die alte Verbindung und macht sofort eine neue auf.

Verbinde ich FHEM mit einem MQTT-Broker auf einem Raspberry, ist dieses Verhalten in der Form nicht erkennbar. Die Verbindung wird aufgebaut und erst mit dem Timeout nach 60 Sekunden wieder geschlossen.

Dann habe ich den MQTT-Broker im Dockercontainer noch über die MQTT.fx App auf meinem iMac angesprochen. Hier habe ich keine Probleme. Ich kann mich verbinden, einen Publish durchführen und bekomme das Topic als Subscriber auch angezeigt. Der Docker-Container scheint also im Grundsatz zu funktionieren.

Worin könnte das Problem mit den ständigen Verbindungsversuchen liegen?

VG
Michael

**Comment by xtolkien** [comment]
Hallo,

wie es scheint, habe ich die Ursache gefunden. Per Default bekommt der MQTT_Server keine Client-Id mitgegeben. Deshalb wird im Modul config.pm von FHEM eine Id generiert. Dies scheint in dieser konkreten Situation das Problem zu sein.

Ich habe jetzt für den Server eine dedizierte Client-Id vergeben. Damit kommt es nicht mehr zu den geschilderten Verbindungsunterbrechungen.

Vg
Michael

**Comment by klein0r** [comment]
Danke für den Hinweis, nehme ich mal mit auf. Hatte das Problem so noch nie

**Comment by Typ1er** [comment]
wie habt ihr das Problem behoben?
