### ISSUE TITLE
FHEM 5.9

### ISSUE THREAD

**Issue by gesicmerrybeard** [klein0r/fhem-docker#16]
Hallo,
beabsichtigst du das Ganze zeitnahe auf FHEM 5.9 zu bringen?
LG

**Comment by petterpet** [comment]
Hallo,
reicht es nicht, die Zeile `ENV FHEM_VERSION 5.8` im Dockerfile in `ENV FHEM_VERSION 5.9` zu ändern?
(Und den Container dann neu zu bauen)
Dann wird die neue Version heruntergeladen und installiert: `RUN wget https://fhem.de/fhem-${FHEM_VERSION}.deb && dpkg -i fhem-${FHEM_VERSION}.deb`
LG

**Comment by klein0r** [comment]
Ja, richtig. Das sollte reichen.
Update ist aber schon in Planung.
Sind ja noch ein paar andere Sachen offen

**Comment by petterpet** [comment]
Habe das ganze gerade in einer Ubuntu-VM getestet. Wenn ich den Container neu baue, bekomme ich bei `dpkg -i fhem-${FHEM_VERSION}.deb` (Zeile 89) 
folgende Fehlermeldung: 
`stat: cannot stat '/sbin/init': No such file or directory
dpkg: error processing package fhem (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 fhem`

Wäre schön, wenn du das ganze zeitnahe beheben könntest, da ich gerne mein Life-Docker-System aufsetzen möchte.

**Comment by dma7** [comment]
Ich habe das gleiche Problem beobachtet. Eine kleine Analyse des deb Paketes hat ergeben, dass in zwei Files (beide in control.tar.gz) daraus, nämlich postinst und prerm, die folgende Code-Zeile nicht funktioniert:

`test=$(stat /sbin/init |grep "/sbin/init")`

Die Zeile hat mit der Erkennung des verwendeten Init-Systems zu tun. Obwohl Debian Stretch (auf dem ja das Image basiert) eigentlich systemd haben sollte, ist in meinem Image /sbin/init nicht vorhanden. Folglicherweise liefert der stat Befehl einen Fehler. Wie man das korrekt löst, weiß ich leider nicht - so fit bin ich nicht in Linux.
Ich würde allerdings mal darauf tippen, dass der Fehler auf der FHEM Seite liegt. Der Code zur Erkennung des Init-Systems sollte robuster gestaltet werden.

--> FHEM_VERSION auf "5.9" zu setzen funktioniert also leider nicht.

**Comment by Quantum1337** [comment]
warum nicht das offizielle image verwenden ?
https://github.com/fhem/fhem-docker

**Comment by klein0r** [comment]
@Quantum1337 Kannst Du gerne machen - das gab es halt noch nicht als dieses Projekt hier ins Leben gerufen wurde 😄

**Comment by Quantum1337** [comment]
@klein0r das sollte kein Vorwurf sein. Nur ein Hinweis darauf, dass es mittlererweile etwas offizielles gibt.

**Comment by klein0r** [comment]
@Quantum1337 Habe ich auch nicht so aufgefasst 👍 Aber ich muss das Repo hier wirklich mal aktualisieren. Nervt mich selbst dass das nicht so auf dem aktuellsten Stand ist.

**Comment by gesicmerrybeard** [comment]
@klein0r Hast du eine Idee wann du ca. dazu kommen wirst ich wollte bald starten und würde sonst schauen ob ich es allein "gefixt" bekomme :)

**Comment by klein0r** [comment]
@frederikkunze Wenn ich mir die Liste mit offenen Punkten so anschaue, ist das ziemlich weit hinten 😄 Wäre cool wenn Du es fixen könntest und dann einen PullRequest stellst.

**Comment by klein0r** [comment]
@Quantum1337 Jetzt basier das compose auch auf dem offiziellen Image
