### ISSUE TITLE
log directory is missing

### ISSUE THREAD

**Issue by dgawin** [klein0r/fhem-docker#19]
hi,

got problems during start of fhem container

`fhem_1      | Preparing configuration ...
fhem_1      | Starting FHEM ...
fhem_1      | Can't open ./log/fhem-2019-01.log: No such file or directory at fhem.pl line 2660.
fhem_1      | Unable to start FHEM process - errorcode 2
fhem_1      | Preparing user environment ...`

create directory "log" in fhem folder solved the issue.

**Comment by klein0r** [comment]
Has been fixed in 72784440c9e40e96602d420c9c19175a97a0da96
