### ISSUE TITLE
Alexa und Reverse Proxy

### ISSUE THREAD

**Issue by Clown007** [klein0r/fhem-docker#2]
Im Video wird erwähnt, dass auch Alexa und der Reverse Proxy integriert sind. Leider ist das hier auf den Seiten nicht so. Gibt es die Ergänzung noch?

**Comment by klein0r** [comment]
Da ich aktuell noch nicht weiß, wie ich das dann mit den Konfigurationsdateien machen soll, ist dies noch nicht aufgenommen worden.

Mein Ziel ist, dass man sehr schnell und einfach alles zum Laufen bekommt. Und wenn man jetzt erst noch Zertifikate generieren müsste usw, geht dieser Gedanke verloren.

Ich könnte aber z.B. die Konfigurationsdateien anlegen und die Container bereitstellen.

**Comment by tigertim08** [comment]
Das wäre super :) Gerade das Thema Alexa würde mich interessieren. Da ich mit Docker noch nicht all zu sehr vertraut bin, ich aber fast alles zuhause über alexa steuere, wäre ich darauf zwingend angewiesen ;)

**Comment by hvorragend** [comment]
Ich kann folgende NGINX-Examples empfehlen:
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#examples

Mit der Variante der getrennten Containern (https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#separate-containers) ist es relativ einfach, einen ReverseProxy davor zu schalten. Man muss sich einlesen und auch ein wenig rumprobieren. Aber schlussendlich muss man auch nur den Skripten dort vertrauen. Die machen das Meiste.
