### ISSUE TITLE
SQL Connection not working

### ISSUE THREAD

**Issue by littlemincer** [klein0r/fhem-docker#20]
Start with standard has a Problem with sql connection
DBI connect('database=fhem;host=mysql;port=3306','fhemuser',...) failed: Access denied for user 'fhemuser''

**Comment by dirkmothes** [comment]
Hi Matthias,

same problem. same configuration like rpi/docker video. no connection to 3306 possible and FHEM cannot connect. 

Hopefully

DIrk

**Comment by zombiegh0st** [comment]
In **environment** section of **mysql** add the folowing to lines to the **docker-compose.yml** and rebuild.
```
- MYSQL_USER=fhemuser
- MYSQL_PASSWORD=2jRHnEi3WuNSQAcX7
```

**Comment by klein0r** [comment]
@zombiegh0st This has already been added to the master branch. Raspberry Pi branch hasn't been update for ages 😞 Pull Requests welcome
