### ISSUE TITLE
Error SQL-Datenbank installation

### ISSUE THREAD

**Issue by fastLion** [klein0r/fhem-docker#22]
Hallo Matthias,
ich habe den Docker Container bei mir auf den Laptop installiert (Manjaro XFCE) und dabei wurde dann bei der Ausführung von 'docker-compose' diese Fehler-Meldung ausgegeben:
ERROR: for mysql  Cannot start service mysql: b'driver failed programming external connectivity on endpoint fhem-docker_mysql_1 (320ba1a96075cb1c273803c82f1b7de923777e6bb2f104633acf539c7d22fcd8): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use'

Nun bin ich relativ neu in dieser Materie und habe mit der Installation, Einrichtung usw. von Datenbanken keine Ahnung. 
Kannst Du mir bitte dabei helfen, dass aus zu sortieren?
Besten Dank
Jens

**Comment by klein0r** [comment]
Ich mach das hier mal zu, da bei mir alles einwandfrei läuft. Habe die Docker-Compose vor ein paar Tagen noch aktualisiert (master branch, Raspberry läuft zur Zeit nicht glaube ich)
