### ISSUE TITLE
standard_init_linux.go:211

### ISSUE THREAD

**Issue by terfurt** [klein0r/fhem-docker#23]
Hallo Mathias, ich versuche dein fhem/docker file zu installieren. Leider bricht die Installationmit der oben genannten Fehlermeldung ab.
`
standard_init_linux.go:211: exec user process caused "exec format error"
ERROR: Service 'habridge' failed to build: The command '/bin/sh -c mkdir -p /opt/habridge && wget https://github.com/bwssytems/ha-bridge/releases/download/v${BRIDGE_VERSION}/ha-bridge-${BRIDGE_VERSION}.jar -O /opt/habridge/ha-bridge-${BRIDGE_VERSION}.jar' returned a non-zero code: 1
`

**Comment by dotWee** [comment]
Diese Fehlermeldung tritt häufig auf wenn Container mit Images auf Basis inkompatibler Architekturen gestartet werden (zB Container mit x86 Image Architektur wird auf ARM Prozessor gestartet).

Auf welcher Prozessorarchitektur willst du die Container starten? 
<sub>(unter Linux mit `$ uname --machine` herausfindbar)</sub>

**Comment by terfurt** [comment]
Danke für deinen Hinweiß, hat sich für mich allerdings erledigt. Habe alles auf Proxmox umgezogen...
