### ISSUE TITLE
DbLog DBLogging failed: Unknown MySQL server host 'mysql' (-2) at ./FHEM/93_DbLog.pm line 3085.

### ISSUE THREAD

**Issue by maddhin** [klein0r/fhem-docker#25]
Hallo,
ich habe das FHEM, etc. nach Anleitung via Docker-compose installiert und bekomme folgenden bzw. folgende Fehler im Event Monitor:

2021-02-10 10:58:56.622 DbLog DBLogging DBI connect('database=fhem;host=mysql;port=3306','fhemuser',...) failed: Can't connect to MySQL server on 'mysql' (115) at ./FHEM/93_DbLog.pm line 3018. 
2021-02-10 10:58:56.622 DbLog DBLogging DBI connect('database=fhem;host=mysql;port=3306','fhemuser',...) failed: Can't connect to MySQL server on 'mysql' (115) at ./FHEM/93_DbLog.pm line 3085. 
2021-02-10 10:58:56.622 DbLog DBLogging connected

Ich kenne mich zu wenig aus, um zu wissen, wo genau der Fehler sein kann. Scheinbar gibt es Probleme bei der Verbindung zur MySQL DB. Hat jemand eine Idee, wie ich diesen Fehler beheben kann?

LG
Martin

**Comment by klein0r** [comment]
Auf was für einem System hast Du denn das Ganze installiert?

**Comment by LMey** [comment]
Rechte würd ich fast ausschließen, da würdest du eher ein ACCESS DENIED bekommen... 

Ist der mysql Server denn gestartet? 

>docker ps -a

**Comment by LMey** [comment]
Kannst du mal kontrollieren ob der mysql Container läuft 

>docker ps -a

Und ob innerhalb des Containers auch der mysql Service oben ist?

Um dich in den Container einzuwählen:
>docker exec -it [ContainerID] /bin/bash 

Dort dann nach mysql suchen 

>ps -lart |grep mysql

**Comment by maddhin** [comment]
> Ist der mysql Server denn gestartet?
> 
> > docker ps -a

super, sehr hilfreich, jetzt kommen wir der Sache näher... mysql wird als "restarting" angezeigt. mysql scheint also ständig neu zu starten :( 

Die mysql logs kann ich im Moment so nicht aufrufen. Jemand eine Idee, wie man mysql stabilisieren kann? 

EDIT: läuft auf einem RPi 1 mit Hypriot

**Comment by maddhin** [comment]
ich habe docker-compose down und docker-compose up gemacht und bei myswl folgende Fehlermeldung:
standard_init_linux.go:219: exec user process caused: exec format error

**Comment by klein0r** [comment]
Auf einem Rasperry Pi nutzt Du dann hoffentlich den anderen branch und nicht den Master?

**Comment by maddhin** [comment]
> 
> 
> Auf einem Rasperry Pi nutzt Du dann hoffentlich den anderen branch und nicht den Master?

ohhh... Sorry, den RPi branch habe ich leider noch nciht gesehen gehabt... Ich gehe mal davon aus, dass der dann funktioniert... 

Lieben Dank für die schnellen Antworten! Super!!

**Comment by klein0r** [comment]
Also das war zumindest mal so 😄 Habe den Branch seit Jahren nicht mehr angefasst.
Könnte gut sein, dass das alle Versionen dort sind.
