### ISSUE TITLE
State-View for MAX-Device looks strange 

### ISSUE THREAD

**Issue by forestvogo** [klein0r/fhem-docker#27]
Hi,
I do run the latest Docker Version of FHEM and for my MAX-Devices the View of the state looks strange:
![image](https://user-images.githubusercontent.com/10856238/161436034-d971497a-7cc1-48b6-b12e-4b714f01cca0.png)
![image](https://user-images.githubusercontent.com/10856238/161436041-e669c758-960e-4854-90da-d4fad8147f8f.png)

I do think it is in the code, where the line with "&deg;C" and thenafter with "°C" is used.

Not sure, why there appears this problem right now.

When I do change the MAX-Device to Auto, it shows "°C". After reloading the Home-Screen it changes back to the attached picture-version.

Thank and best regards
Volker

**Comment by klein0r** [comment]
This is not related to this repository.
