### ISSUE TITLE
Rasbian MySQL

### ISSUE THREAD

**Issue by lubeda** [klein0r/fhem-docker#5]
Hallo,
in der Datei  /opt/fhem/contrib/dblog/db.conf sollte dieser Text stehen
`################################################################
%dbconfig= (
        connection => "mysql:database=fhem;host=mysql;port=3306",
        user => "fhemuser",
        password => "2jRHnEi3WuNSQAcX7",
);
################################################################
`
wahrscheinlich wird dieLogDB auch nicht automatisch angelegt.

**Comment by raxorgit** [comment]
Besten Dank! :-) @lubeda
