### ISSUE TITLE
node-red startet nicht 

### ISSUE THREAD

**Issue by fischl3r** [klein0r/fhem-docker#7]
Nach einem 
docker-compose build
docker-compose up

startet node-red nicht 

Fehlermeldung
`nodered_1   | 17 Dec 16:26:08 - [error] Failed to start server:`
`nodered_1   | 17 Dec 16:26:08 - [error] Error: EACCES: permission denied, mkdir '/data/lib/flows'`
`nodered_1   |     at Error (native)`
`fhemdocker_nodered_1 exited with code 0`

Nachdem ich die Ordner lib/flows/ im data Ordner erstellt habe funktioniert es.
 
Trotzdem TOP Arbeit - Danke !!!

**Comment by frankiesoc** [comment]
Hey fischl3r,
das Problem hatte ich auch, scheint ein Rechterhema zu sein.
Entweder der Ordner per Hand anlegen oder der node-red Instanz die root Rechte geben.
Grüße

**Comment by fischl3r** [comment]
Hallo frankiesoc

ja es ist ein Rechteprobleme.
Wenn man in der "docker-compose.yml" explizit den User angibt geht es.

`image: nodered/node-red-docker:0.17.5`
`user: "1000"`
`volumes:`
`- ./nodered/data/:/data/`

Danke für die schnelle Hilfe
